[[shader-modules]]
name = "triangle"
path = "triangle.wgsl"

[[bind-groups]]
layout = "camera"

[vertex-shader]
shader-module = "triangle"
entrypoint = "vs_main"

[[vertex-shader.buffers]]
step-mode = "vertex"
attributes = [
    # Position
    { format = "f32x2" },
    # Color (rgba)
    { format = "f32x4" }
]

[[vertex-shader.buffers]]
step-mode = "instance"
attributes = [
    # Transformation matrix
    { format = "f32x4" },
    { format = "f32x4" },
    { format = "f32x4" },
    { format = "f32x4" }
]

[fragment-shader]
shader-module = "triangle"
entrypoint = "fs_main"

[[fragment-shader.targets]]
format = "surface"
