name: Deploy WASM web app to Github Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/install@v0.1.2
        with:
          crate: trunk
          use-tool-cache: true
      - run: rustup default nightly
      - run: rustup target add wasm32-unknown-unknown
      - uses: actions/checkout@v3
      - working-directory: meteors
        run: trunk build --release --public-url /krill-engine
      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: meteors/dist
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        id: deployments
        uses: actions/deploy-pages@v1
